/**
 * Every word the portal shows, in Spanish (default) and English (a person whose
 * portal language is "en"). Neutral imperatives, per docs/DESIGN.md section 5.
 */
export type Lang = "es" | "en";

const plural = (n: number, one: string, many: string) => `${n} ${n === 1 ? one : many}`;

const es = {
  portal: "Afiliados",
  navClients: "Clientes",
  navRegister: "Registrar",
  navRenew: "Renovar",
  navEarnings: "Ganancias",
  signOut: "Salir",
  test: "PRUEBA",
  brand: "Hoy",
  role: "Afiliado",

  // Clients
  navMyClients: "Mis clientes",
  clientsSub: (name: string, due: number) =>
    due === 0 ? `Hola, ${name}.` : `Hola, ${name}. ${due === 1 ? "1 cliente para renovar pronto." : `${due} clientes para renovar pronto.`}`,
  statActive: "Activos",
  statLapsed: "Vencidos",
  today: "hoy",
  next30Days: "vencen en los próximos 30 días",
  renewWithCode: "Renovar con código",
  colAction: "Acción",
  clientsTitle: "Mis clientes",
  registerClient: "Registrar cliente",
  dueCaption: "Renovar pronto",
  allCaption: "Todos mis clientes",
  noClients: "Todavía no tienes clientes registrados.",
  colName: "Nombre",
  colCode: "Código",
  colCountry: "País",
  colRegion: "Departamento / parroquia",
  colStatus: "Estado",
  colPeriodEnd: "Fin del período",
  colDaysLeft: "Quedan",
  statusActive: "Activo",
  statusDue: "Renovar pronto",
  statusLapsed: "Vencido",
  statusNone: "Sin pago",
  inactive: "Desactivado",
  daysLeft: (n: number) => (n === 0 ? "Vence hoy" : n === 1 ? "1 día" : `${n} días`),
  renewLink: "Renovar",
  renewLinkFor: (name: string) => `Renovar a ${name}`,

  // Register
  registerTitle: "Registrar cliente",
  chooseCountry: "¿De qué país es el cliente?",
  registerStep1: "Paso 1 de 2: el país del cliente.",
  registerStep2: (country: string) => `Paso 2 de 2: los datos del cliente de ${country}.`,
  changeCountry: "Cambiar país",
  fullName: "Nombre completo",
  team: "Equipo de fútbol",
  choose: "Elige una opción",
  noTeam: "Ninguno",
  submitRegister: "Registrar y generar código",
  saleNote: "Registrar es una venta: hazlo solo cuando el cliente te haya pagado $20.00 por 6 meses.",
  errName: "Escribe el nombre completo del cliente.",
  errRegion: "Elige de la lista.",
  errTeam: "Elige un equipo o «Ninguno».",
  errCountry: "Elige el país del cliente.",
  errCode: "No se pudo generar un código. Inténtalo otra vez.",
  errRejected: "La base de datos no aceptó el registro. Revisa los datos e inténtalo otra vez.",

  // Code page
  codeTitle: "Código del cliente",
  codeFor: "Código de",
  codeSub: "Dale este código al cliente: es su cuenta de Hoy.",
  codeDetails: "Datos del cliente",
  neverUsed: "Nunca usamos las letras O, I, L, S, U ni los números 0, 1, 5, 8.",
  periodEnds: "Pagado hasta",
  print: "Imprimir",
  registerAnother: "Registrar otro",
  backToClients: "Ver mis clientes",

  // Renew: enter the code
  renewTitle: "Renovar cliente",
  renewSub: "Cualquier cliente de Hoy, con el código de su recibo.",
  renewStatusSub: "Revisa los datos con el cliente antes de cobrar.",
  renewIntro: "Escribe el código del recibo del cliente. Sirve para cualquier cliente de Hoy, aunque lo haya registrado otro negocio. La comisión de la renovación es tuya.",
  renewCodeLabel: "Código del cliente",
  renewFind: "Buscar cliente",
  errLookupInvalid: "Ese código no es válido. Son 8 letras y números, como ACDE-FG34.",
  errLookupNotFound: "No hay ningún cliente con ese código. Revísalo con el cliente.",
  errLookupThrottled: "Demasiados códigos que no existen. Espera 15 minutos antes de buscar otra vez.",

  // Renew: the client's status
  renewNoPeriod: "Sin periodo pagado",
  expiresIn: (n: number) => (n <= 0 ? "Vence hoy" : n === 1 ? "Vence en 1 día" : `Vence en ${n} días`),
  registeredBy: (name: string) => `Registrado por: ${name}`,
  registeredByYou: "Registrado por: ti",
  registeredByHouse: "Registrado por: Hoy (registro directo)",
  whatItBuys: "Lo que paga este cobro",
  newPeriod: (from: string, to: string) => `Nuevo periodo: ${from} – ${to}`,
  startsTodayLapsed: "Empieza hoy, porque el periodo anterior ya terminó. La cuenta se activa en cuanto renuevas.",
  startsTodayNone: "Empieza hoy, porque no tiene ningún periodo pagado. La cuenta se activa en cuanto renuevas.",
  extendsFromEnd: "Se suma al periodo actual: empieza cuando termina el que ya pagó, así no pierde ningún día.",
  yourCommission: (money: string) => `Tu comisión: ${money}`,
  noCommission: "Sin comisión",
  clientInactive: "Esta cuenta está desactivada. Habla con Hoy.",
  recentWarning: (when: string, until: string, byYou: boolean) =>
    `Este cliente ya se renovó hace un momento (${when}${byYou ? ", lo cobraste tú" : ""}), pagado hasta el ${until}. Si cobras otra vez, se suman otros 6 meses.`,
  recentWarningGeneric: "Este cliente ya se renovó hace un momento. Si cobras otra vez, se suman otros 6 meses.",
  confirmRepeat: "Sí, cobrar otros 6 meses",
  renewNote: "Renueva solo cuando el cliente ya te haya pagado.",
  collectButton: (money: string) => `Cobré ${money} — renovar`,
  findAnother: "Buscar otro código",

  // Renew: done
  renewedTitle: "Renovado",
  voidedTitle: "Renovación anulada",
  voidedNote: "Hoy anuló esta renovación. No cuenta como pagada.",
  accountActive: "La cuenta ya está activa.",
  reactivated: "La cuenta estaba vencida y se reactivó con este pago.",
  collectedByYou: "Cobrado por: ti",
  amountPaid: (money: string) => `Cantidad: ${money}`,
  paidAt: (when: string) => `Fecha: ${when}`,
  renewAnother: "Renovar otro",
  receiptFor: (name: string) => `Recibo de ${name}.`,
  receiptDetails: "Detalles del cobro",

  // Earnings
  earningsTitle: "Mis ganancias",
  earned: "Ganado",
  earnedThisMonth: "Ganado este mes",
  paidOut: "Pagado a ti",
  owed: "Por pagarte",
  statRegistrationsLabel: "Registros",
  statRenewalsLabel: "Renovaciones",
  totalsTitle: "Totales",
  sinceStart: "desde tu primer registro",
  asOfToday: "a hoy",
  statRegistrations: (n: number) => `ganado en ${plural(n, "registro", "registros")}`,
  statRenewals: (n: number) => `ganado en ${plural(n, "renovación", "renovaciones")}`,
  statRenewalsSplit: (own: number, other: number, otherMoney: string) =>
    `${own} de tus clientes · ${other} de clientes de otros negocios (${otherMoney})`,
  renewAnywhere: (money: string) =>
    `Cualquier cliente de Hoy puede renovar contigo, y la comisión es tuya: ${money} por cada renovación que cobras, aunque lo haya registrado otro negocio. Registrar te da la comisión del registro; cada renovación que cobras te da la de esa renovación.`,
  renewedElsewhere: (n: number) =>
    n === 1
      ? "1 renovación de tus clientes se hizo en otro negocio o con Hoy. Cuando le toque renovar otra vez, puede hacerlo contigo."
      : `${n} renovaciones de tus clientes se hicieron en otro negocio o con Hoy. Cuando les toque renovar otra vez, pueden hacerlo contigo.`,
  allCad: "Todas las cantidades en dólares canadienses (CAD).",
  renewalsCaption: "Renovaciones que cobraste",
  renewalsLatest: (n: number) => `Renovaciones que cobraste, las ${n} más recientes`,
  noRenewals: "Todavía no has cobrado ninguna renovación.",
  registrationsCaption: "Tus registros",
  registrationsLatest: (n: number) => `Tus registros, los ${n} más recientes`,
  noRegistrations: "Todavía no tienes registros.",
  colDate: "Fecha",
  colClient: "Cliente",
  colPeriod: "Periodo",
  colAmount: "Comisión",
  colCharged: "Cantidad",
  colRegisteredBy: "Registrado por",
  youShort: "ti",
  periodRange: (from: string, to: string) => `${from} – ${to}`,
  payoutsCaption: "Pagos que has recibido",
  noPayouts: "Todavía no hay pagos registrados a tu nombre.",
  colMethod: "Forma de pago",
  colNote: "Nota",

  // Sign-in and setup
  loginTitle: "Entrar",
  login: "Usuario",
  password: "Contraseña",
  enter: "Entrar",
  setupDone: "Contraseña guardada. Ya puedes entrar.",
  errInvalid: "Usuario o contraseña incorrectos.",
  errInactive: "Esta cuenta está desactivada. Habla con el propietario.",
  errThrottled: "Demasiados intentos. Espera 15 minutos.",
  errSetupRequired: "Esta cuenta aún no tiene contraseña. Usa el enlace que te dio el propietario.",
  setupTitle: "Crea tu contraseña",
  newPassword: "Contraseña nueva (al menos 10 caracteres)",
  repeatPassword: "Repite la contraseña",
  savePassword: "Guardar contraseña",
  errWeak: "La contraseña debe tener al menos 10 caracteres.",
  errMismatch: "Las dos contraseñas no coinciden.",
  errInvalidToken: "Este enlace no es válido o ya se usó. Pide uno nuevo al propietario.",
  errExpired: "Este enlace venció. Pide uno nuevo al propietario.",
  setupSignIn: "Si ya creaste tu contraseña, entra aquí",

  notFound: "No encontramos esta página.",
  serverError: "Algo falló. No mostramos datos que no pudimos confirmar. Inténtalo otra vez.",
};

export type Strings = typeof es;

const en: Strings = {
  portal: "Affiliates",
  navClients: "Clients",
  navRegister: "Register",
  navRenew: "Renew",
  navEarnings: "Earnings",
  signOut: "Sign out",
  test: "TEST",
  brand: "Hoy",
  role: "Affiliate",

  navMyClients: "My clients",
  clientsSub: (name: string, due: number) =>
    due === 0 ? `Hello, ${name}.` : `Hello, ${name}. ${due === 1 ? "1 client to renew soon." : `${due} clients to renew soon.`}`,
  statActive: "Active",
  statLapsed: "Lapsed",
  today: "today",
  next30Days: "ending in the next 30 days",
  renewWithCode: "Renew with a code",
  colAction: "Action",
  clientsTitle: "My clients",
  registerClient: "Register client",
  dueCaption: "Renew soon",
  allCaption: "All my clients",
  noClients: "You have no clients registered yet.",
  colName: "Name",
  colCode: "Code",
  colCountry: "Country",
  colRegion: "Department / parish",
  colStatus: "Status",
  colPeriodEnd: "Period ends",
  colDaysLeft: "Left",
  statusActive: "Active",
  statusDue: "Renew soon",
  statusLapsed: "Lapsed",
  statusNone: "Not paid",
  inactive: "Deactivated",
  daysLeft: (n: number) => (n === 0 ? "Ends today" : n === 1 ? "1 day" : `${n} days`),
  renewLink: "Renew",
  renewLinkFor: (name: string) => `Renew ${name}`,

  registerTitle: "Register client",
  chooseCountry: "Which country is the client from?",
  registerStep1: "Step 1 of 2: the client's country.",
  registerStep2: (country: string) => `Step 2 of 2: the details of the client from ${country}.`,
  changeCountry: "Change country",
  fullName: "Full name",
  team: "Football team",
  choose: "Choose one",
  noTeam: "None",
  submitRegister: "Register and issue code",
  saleNote: "Registering is a sale: do it only once the client has paid you $20.00 for 6 months.",
  errName: "Enter the client's full name.",
  errRegion: "Choose from the list.",
  errTeam: "Choose a team or “None”.",
  errCountry: "Choose the client's country.",
  errCode: "Could not issue a code. Try again.",
  errRejected: "The database did not accept this registration. Check the details and try again.",

  codeTitle: "Client code",
  codeFor: "Code for",
  codeSub: "Give this code to the client: it is their Hoy account.",
  codeDetails: "Client details",
  neverUsed: "We never use the letters O, I, L, S, U or the digits 0, 1, 5, 8.",
  periodEnds: "Paid until",
  print: "Print",
  registerAnother: "Register another",
  backToClients: "See my clients",

  renewTitle: "Renew client",
  renewSub: "Any Hoy client, by the code on their receipt.",
  renewStatusSub: "Check the details with the client before collecting.",
  renewIntro: "Type the code from the client's receipt. It works for any Hoy client, even one another business registered. The renewal commission is yours.",
  renewCodeLabel: "Client code",
  renewFind: "Find client",
  errLookupInvalid: "That code is not valid. It is 8 letters and digits, like ACDE-FG34.",
  errLookupNotFound: "No client has that code. Check it with the client.",
  errLookupThrottled: "Too many codes that do not exist. Wait 15 minutes before searching again.",

  renewNoPeriod: "No paid period",
  expiresIn: (n: number) => (n <= 0 ? "Ends today" : n === 1 ? "Ends in 1 day" : `Ends in ${n} days`),
  registeredBy: (name: string) => `Registered by: ${name}`,
  registeredByYou: "Registered by: you",
  registeredByHouse: "Registered by: Hoy (direct registration)",
  whatItBuys: "What this payment buys",
  newPeriod: (from: string, to: string) => `New period: ${from} – ${to}`,
  startsTodayLapsed: "It starts today, because the last period has ended. The account is active as soon as you renew.",
  startsTodayNone: "It starts today, because there is no paid period. The account is active as soon as you renew.",
  extendsFromEnd: "It adds on to the current period: it starts when the paid one ends, so no day is lost.",
  yourCommission: (money: string) => `Your commission: ${money}`,
  noCommission: "No commission",
  clientInactive: "This account is deactivated. Talk to Hoy.",
  recentWarning: (when: string, until: string, byYou: boolean) =>
    `This client was renewed a moment ago (${when}${byYou ? ", collected by you" : ""}), paid until ${until}. Collecting again adds another 6 months.`,
  recentWarningGeneric: "This client was renewed a moment ago. Collecting again adds another 6 months.",
  confirmRepeat: "Yes, collect another 6 months",
  renewNote: "Renew only once the client has paid you.",
  collectButton: (money: string) => `I collected ${money} — renew`,
  findAnother: "Look up another code",

  renewedTitle: "Renewed",
  voidedTitle: "Renewal voided",
  voidedNote: "Hoy voided this renewal. It does not count as paid.",
  accountActive: "The account is active now.",
  reactivated: "The account had lapsed and this payment reactivated it.",
  collectedByYou: "Collected by: you",
  amountPaid: (money: string) => `Amount: ${money}`,
  paidAt: (when: string) => `Date: ${when}`,
  renewAnother: "Renew another",
  receiptFor: (name: string) => `Receipt for ${name}.`,
  receiptDetails: "Payment details",

  earningsTitle: "My earnings",
  earned: "Earned",
  earnedThisMonth: "Earned this month",
  paidOut: "Paid to you",
  owed: "Owed to you",
  statRegistrationsLabel: "Registrations",
  statRenewalsLabel: "Renewals",
  totalsTitle: "Totals",
  sinceStart: "since your first registration",
  asOfToday: "as of today",
  statRegistrations: (n: number) => `earned from ${plural(n, "registration", "registrations")}`,
  statRenewals: (n: number) => `earned from ${plural(n, "renewal", "renewals")}`,
  statRenewalsSplit: (own: number, other: number, otherMoney: string) =>
    `${own} of your clients · ${other} of other businesses' clients (${otherMoney})`,
  renewAnywhere: (money: string) =>
    `Any Hoy client can renew with you, and the commission is yours: ${money} for each renewal you collect, even if another business registered them. Registering earns you the registration; each renewal you collect earns you that renewal.`,
  renewedElsewhere: (n: number) =>
    n === 1
      ? "1 renewal of your clients was made at another business or with Hoy. Next time it is due, it can be with you."
      : `${n} renewals of your clients were made at another business or with Hoy. Next time they are due, they can be with you.`,
  allCad: "All amounts in Canadian dollars (CAD).",
  renewalsCaption: "Renewals you collected",
  renewalsLatest: (n: number) => `Renewals you collected, the ${n} most recent`,
  noRenewals: "You have not collected a renewal yet.",
  registrationsCaption: "Your registrations",
  registrationsLatest: (n: number) => `Your registrations, the ${n} most recent`,
  noRegistrations: "You have no registrations yet.",
  colDate: "Date",
  colClient: "Client",
  colPeriod: "Period",
  colAmount: "Commission",
  colCharged: "Amount",
  colRegisteredBy: "Registered by",
  youShort: "you",
  periodRange: (from: string, to: string) => `${from} – ${to}`,
  payoutsCaption: "Payments you have received",
  noPayouts: "No payments to you have been recorded yet.",
  colMethod: "Method",
  colNote: "Note",

  loginTitle: "Sign in",
  login: "Username",
  password: "Password",
  enter: "Sign in",
  setupDone: "Password saved. You can sign in now.",
  errInvalid: "Wrong username or password.",
  errInactive: "This account is deactivated. Talk to the owner.",
  errThrottled: "Too many tries. Wait 15 minutes.",
  errSetupRequired: "This account has no password yet. Use the link the owner gave you.",
  setupTitle: "Create your password",
  newPassword: "New password (at least 10 characters)",
  repeatPassword: "Repeat the password",
  savePassword: "Save password",
  errWeak: "The password must be at least 10 characters.",
  errMismatch: "The two passwords do not match.",
  errInvalidToken: "This link is not valid or was already used. Ask the owner for a new one.",
  errExpired: "This link has expired. Ask the owner for a new one.",
  setupSignIn: "If you already set your password, sign in here",

  notFound: "We could not find this page.",
  serverError: "Something failed. We do not show data we could not confirm. Try again.",
};

export const STRINGS: Record<Lang, Strings> = { es, en };

export const strings = (lang: string | null | undefined): Strings => (lang === "en" ? en : es);

/** "septiembre de 2026" / "September 2026", in Leamington time. */
export function monthLabel(now: Date, lang: Lang): string {
  return new Intl.DateTimeFormat(lang === "en" ? "en-CA" : "es-MX", {
    month: "long", year: "numeric", timeZone: "America/Toronto",
  }).format(now);
}
