-- Jamaica: towns and communities (GeoNames populated places), by parish.
--
-- Places with population > 0 plus parish capitals, so workers can find their community.
-- Parish names match municipalities_jm.sql. Rows already in that hand-written file are omitted here,
-- so this file never moves their coordinates. Names: "Saint X" -> "St. X", curly apostrophes straightened.
--
-- Source:      GeoNames country dumps, https://download.geonames.org/export/dump/
-- Licence:     Creative Commons Attribution 4.0, https://creativecommons.org/licenses/by/4.0/
-- Attribution: Contains data from GeoNames, CC BY 4.0
-- Downloaded:  2026-09-13
-- Generated by: node packages/db/scripts/build-municipalities.mjs --src <geonames dump dir>
--               (do not edit by hand; re-run the generator)
-- Rows:        91
-- Duplicates dropped on (country, admin_region, name): 0
-- Skipped (no usable point / no region): 0
--
-- Re-running corrects coordinates, timezone and population in place.

begin;

insert into municipalities (country, admin_region, name, lat, lng, population, timezone) values
  ('JM', 'Clarendon', 'Chapelton', 18.08333, -77.26667, 4514, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Hayes', 17.87569, -77.23711, 9701, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Kellits', 18.17278, -77.23083, 2631, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Limit', 18.15287, -77.47121, 2321, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Lionel Town', 17.81007, -77.24061, 5362, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Race Course', 17.836, -77.2855, 2974, 'America/Jamaica'),
  ('JM', 'Clarendon', 'Rocky Point', 17.774, -77.26107, 3152, 'America/Jamaica'),
  ('JM', 'Hanover', 'Barbican', 18.45038, -78.10142, 10337, 'America/Jamaica'),
  ('JM', 'Hanover', 'Cascade', 18.39747, -78.10337, 1232, 'America/Jamaica'),
  ('JM', 'Hanover', 'Lucea', 18.45095, -78.17356, 7377, 'America/Jamaica'),
  ('JM', 'Hanover', 'Orange Bay', 18.3667, -78.30754, 2546, 'America/Jamaica'),
  ('JM', 'Hanover', 'Sandy Bay', 18.44854, -78.07321, 4520, 'America/Jamaica'),
  ('JM', 'Kingston', 'Port Royal', 17.93738, -76.84062, 3327, 'America/Jamaica'),
  ('JM', 'Manchester', 'Alligator Pond', 17.86932, -77.56769, 1793, 'America/Jamaica'),
  ('JM', 'Manchester', 'Coleyville', 18.20783, -77.50754, 3860, 'America/Jamaica'),
  ('JM', 'Manchester', 'Porus', 18.03535, -77.41166, 5923, 'America/Jamaica'),
  ('JM', 'Manchester', 'Williamsfield', 18.06667, -77.46667, 3255, 'America/Jamaica'),
  ('JM', 'Portland', 'Buff Bay', 18.23287, -76.66118, 2757, 'America/Jamaica'),
  ('JM', 'Portland', 'Hope Bay', 18.19882, -76.56539, 1666, 'America/Jamaica'),
  ('JM', 'Portland', 'Manchioneal', 18.04444, -76.27735, 2321, 'America/Jamaica'),
  ('JM', 'Portland', 'Moore Town', 18.07767, -76.42577, 1119, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Constant Spring', 18.05078, -76.79372, 12830, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Gordon Town', 18.03578, -76.71783, 1088, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Mavis Bank', 18.03111, -76.65792, 1821, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Mona Heights', 18.01375, -76.75186, 2887, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Mountain View Gardens', 17.98559, -76.76714, 10285, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'New Kingston', 18.00747, -76.78319, 583958, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Penwood', 18.00982, -76.83347, 11563, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Stony Hill', 18.07716, -76.79, 8551, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Torrington Park', 17.98878, -76.79426, 11905, 'America/Jamaica'),
  ('JM', 'St. Andrew', 'Tower Hill', 18.0128, -76.65098, 12184, 'America/Jamaica'),
  ('JM', 'St. Ann', 'Alexandria', 18.30768, -77.35335, 1927, 'America/Jamaica'),
  ('JM', 'St. Ann', 'Bamboo', 18.39216, -77.26429, 4264, 'America/Jamaica'),
  ('JM', 'St. Ann', 'Discovery Bay', 18.45873, -77.39997, 8257, 'America/Jamaica'),
  ('JM', 'St. Ann', 'Moneague', 18.27556, -77.11177, 3319, 'America/Jamaica'),
  ('JM', 'St. Ann', 'Runaway Bay', 18.45962, -77.3357, 12358, 'America/Jamaica'),
  ('JM', 'St. Ann', 'St. Ann''s Bay', 18.43581, -77.20098, 13671, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Above Rocks', 18.10678, -76.87608, 5261, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Bog Walk', 18.10205, -77.00541, 12873, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Ewarton', 18.18333, -77.08536, 12797, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Linstead', 18.13683, -77.03171, 20660, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Lluidas Vale', 18.12756, -77.14881, 3163, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Old Harbour', 17.94144, -77.10898, 26024, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Old Harbour Bay', 17.90918, -77.09718, 7912, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Point Hill', 18.08988, -77.10759, 5344, 'America/Jamaica'),
  ('JM', 'St. Catherine', 'Riversdale', 18.16586, -76.96417, 4085, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Accompong', 18.22627, -77.7536, 788, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Balaclava', 18.17228, -77.64375, 2862, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Black River', 18.02636, -77.84873, 4229, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Bull Savannah', 17.88678, -77.59022, 6962, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Lacovia', 18.09356, -77.769, 2760, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Maggotty', 18.16129, -77.76457, 1371, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Malvern', 17.96667, -77.7, 3291, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Nain', 17.96526, -77.60528, 2394, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Santa Cruz', 18.05336, -77.69836, 8217, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Siloah', 18.16709, -77.70348, 2725, 'America/Jamaica'),
  ('JM', 'St. Elizabeth', 'Southfield', 17.8878, -77.66713, 2695, 'America/Jamaica'),
  ('JM', 'St. James', 'Anchovy', 18.4103, -77.93166, 4161, 'America/Jamaica'),
  ('JM', 'St. James', 'Barrett Town', 18.51491, -77.80178, 17169, 'America/Jamaica'),
  ('JM', 'St. James', 'Cambridge', 18.31326, -77.90252, 3119, 'America/Jamaica'),
  ('JM', 'St. James', 'Maroon Town', 18.34464, -77.79544, 3085, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Annotto Bay', 18.2717, -76.76523, 5504, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Gayle', 18.32642, -77.00971, 3305, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Islington', 18.30922, -76.85482, 2958, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Lucky Hill', 18.31002, -77.01491, 774, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Oracabessa', 18.40319, -76.94641, 4100, 'America/Jamaica'),
  ('JM', 'St. Mary', 'Richmond', 18.25478, -76.88799, 2046, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Bath', 17.9482, -76.34916, 2382, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Dalvey', 17.91184, -76.24864, 3037, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Easington', 17.92397, -76.58824, 2634, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Golden Grove', 17.93361, -76.27254, 3058, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Morant Bay', 17.88145, -76.40927, 9368, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Seaforth', 17.93578, -76.4573, 4550, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Trinity Ville', 17.96076, -76.51427, 2895, 'America/Jamaica'),
  ('JM', 'St. Thomas', 'Yallahs', 17.8748, -76.56245, 7644, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Albert Town', 18.29434, -77.54239, 3449, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Clarks Town', 18.4182, -77.54632, 2606, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Duncans', 18.468, -77.53633, 5153, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Falmouth', 18.49358, -77.65587, 7779, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Sherwood Content', 18.39116, -77.62834, 1499, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Ulster Spring', 18.31482, -77.52067, 1411, 'America/Jamaica'),
  ('JM', 'Trelawny', 'Wakefield', 18.41211, -77.72183, 2763, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Bethel Town', 18.29503, -77.95112, 2416, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Bluefields', 18.16602, -78.02702, 2828, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Darliston', 18.23731, -77.97626, 2076, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Frome', 18.29407, -78.15469, 993, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Grange Hill', 18.31062, -78.18431, 10429, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Little London', 18.2483, -78.21641, 4954, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Petersfield', 18.26158, -78.07117, 3454, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Whitehouse', 18.09342, -77.96711, 3233, 'America/Jamaica'),
  ('JM', 'Westmoreland', 'Whithorn', 18.26379, -78.03328, 4284, 'America/Jamaica')
on conflict (country, admin_region, name) do update set lat = excluded.lat, lng = excluded.lng, timezone = excluded.timezone, population = excluded.population;

commit;
